// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkclK74wG8JCZn0XACcUNMUuUGwzv3R6k',
    appId: '11:814284264580:android:755733172a03fcd010ded1',
    messagingSenderId: '814284264580',
    projectId: 'mobileproject-e8063',
    authDomain: 'shopping-app-123454321.firebaseapp.com',
    storageBucket: 'mobileproject-e8063.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkclK74wG8JCZn0XACcUNMUuUGwzv3R6k',
    appId: '11:814284264580:android:755733172a03fcd010ded1',
    messagingSenderId: '814284264580',
    projectId: 'mobileproject-e8063',
    authDomain: 'mobileproject-123454321.firebaseapp.com',
    storageBucket: 'mobileproject-e8063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkclK74wG8JCZn0XACcUNMUuUGwzv3R6k',
    appId: '11:814284264580:android:755733172a03fcd010ded1',
    messagingSenderId: '814284264580',
    projectId: 'mobileproject-e8063',
    authDomain: 'mobileproject-123454321.firebaseapp.com',
    storageBucket: 'mobileproject-e8063.appspot.com',
    iosClientId: '1054303905004-qllrklltf2rtqv1uq508lje00hr90ubq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileprojectShaimaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkclK74wG8JCZn0XACcUNMUuUGwzv3R6k',
    appId: '11:814284264580:android:755733172a03fcd010ded1',
    messagingSenderId: '814284264580',
    projectId: 'mobileproject-e8063',
    authDomain: 'mobileproject-123454321.firebaseapp.com',
    storageBucket: 'mobileproject-e8063.appspot.com',
    iosClientId: '1054303905004-mvig8vak6s2le5mt06287786t9c6g9s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileprojectShaimaa.RunnerTests',
  );
}
